Site1/Models/Result.cs
namespace Site1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Result")]
    public partial class Result
    {
        public int Id { get; set; }

        public int SolutionId { get; set; }

        public int TestId { get; set; }

        [Required]
        [StringLength(56)]
        public string UserId { get; set; }

        [Column("Result", TypeName = "text")]
        public string Result1 { get; set; }

        public DateTime Date { get; set; }

        public virtual Tests Tests { get; set; }

        public virtual solutions solutions { get; set; }
    }
}

Site1/Controllers/InputController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.SqlClient;
using Site1.Models;
using System.Diagnostics;
using System.Threading;
using System.Web.Security;

namespace Site1.Controllers
{
    class PSRunner
    {
        public string Message = "";
        public bool IsRunning = false;
        public Process p;
        public PSRunner()
        { }

        public void Run(string psname, string arguments)
        {
            Message = "";
            p = new Process();
            p.StartInfo.Arguments = arguments;
            p.StartInfo.UseShellExecute = false;
            p.StartInfo.FileName = psname;
            p.StartInfo.CreateNoWindow = false;
            p.StartInfo.RedirectStandardError = false;
            p.StartInfo.RedirectStandardInput = false;
            p.StartInfo.RedirectStandardOutput = true;
            p.OutputDataReceived += new DataReceivedEventHandler
            (
                delegate(object sender, DataReceivedEventArgs e)
                {
                    if (e != null && e.Data != null)
                        Message = e.Data.ToString();
                }
            );

            p.Start();

            IsRunning = true;
            p.BeginOutputReadLine();
            p.WaitForExit(1000);
            try
            {
                p.Kill();
            }
            catch (Exception ex)
            {
            }
            finally
            {
                IsRunning = false;
            }
        }
    }

    public class InputController : Controller
    {
        //
        // GET: /Input/

       // [Authorize(Roles = "Admin, Student")]
        public ActionResult Student()
        {
            ViewBag.Message = "Вход для студентов";

            ServerModel sc = new ServerModel();
            IEnumerable<Site1.Models.solutions> Sol = sc.solutions;
            ViewData["ListSolution"] = Sol;
            return View();
        }

       // [Authorize(Roles = "Admin, Student")]
        public ActionResult Result()
        {
            ViewBag.Message = "Результаты";
            return View();
        }

       // [Authorize(Roles = "Admin, Teacher")]
        public ActionResult Teacher()
        {
            ViewBag.Message = "Вход для преподавателей";
            ServerModel sm = new ServerModel();
            IEnumerable<Site1.Models.solutions> Sol = sm.solutions;
            ViewBag.Solutions = Sol;
            return View();
        }

        //[Authorize(Roles = "Admin")]
        public ActionResult Admin()
        {
            ViewBag.Message = "Вход для администраторов";
            UsersContext uc = new UsersContext();
            IEnumerable<Site1.Models.UserProfile> Users = uc.UserProfiles.ToArray();
            ViewBag.Users = Users;
            return View();
        }

       // [Authorize(Roles = "Admin, Teacher")]
        [HttpPost]
        public ActionResult EditSolution(int SolId)
        {
            ServerModel sm = new ServerModel();
            Site1.Models.solutions sol = sm.solutions.First(x=>x.Id==SolId);
            ViewBag.Title = "Редактирование задания";
            ViewBag.Solution = sol;
            return View("EditSolution");
        }

       // [Authorize(Roles = "Admin, Teacher")]
        [HttpPost]
        public ActionResult ViewTests(int SolId)
        {
            ServerModel sm = new ServerModel();
            IEnumerable<Site1.Models.Tests> T = sm.Tests.Where(x => x.Solution == SolId).ToList();
            ViewBag.Title = "Просмотр тестов задания";
            ViewBag.Tests = T;
            ViewBag.Mess = sm.solutions.First(x => x.Id == SolId).Name;
            return View("ViewTests");
        }

       // [Authorize(Roles = "Admin, Student")]
        [HttpPost]
        public ActionResult ViewResults(int SolId)
        {
            ServerModel sm = new ServerModel();
            IEnumerable<Site1.Models.Result> R = sm.Result.Where(x => x.SolutionId == SolId).ToList();
            ViewBag.Title = "Просмотр результатов";
            ViewBag.Results = R;
            ViewBag.Mess = sm.solutions.First(x => x.Id == SolId).Name;
            return View("ViewResults");
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult UpdateSolution(int Id, string Name, string Description)
        {
            ServerModel sm = new ServerModel();
            Site1.Models.solutions source = sm.solutions.First(x => x.Id == Id);
            
            Site1.Models.solutions updated = new solutions();
            updated.Id = source.Id;
            updated.Name = Name;
            updated.Description = Description;

            sm.Entry(source).CurrentValues.SetValues(updated);
            sm.SaveChanges();

            return RedirectPermanent("Teacher");
        }

        [Authorize]
        [HttpPost]
        public ActionResult UploadFile(IEnumerable<HttpPostedFileBase> fileUpload)
        {
            if (fileUpload.Count() != 0)
            {
                int SolId = 3;
                HttpPostedFileBase file = fileUpload.First();

                string path = AppDomain.CurrentDomain.BaseDirectory + "UploadedFiles/";
                string filename = Path.GetFileName(file.FileName);
                string newFileName = String.Format("Thumbnail_{0}_{1}.exe", DateTime.Now.ToString("yyyyMMddHHmmssfff"), Guid.NewGuid());

                if (filename != null) file.SaveAs(Path.Combine(path, newFileName));

                ServerModel sc = new ServerModel();
                IEnumerable<Site1.Models.Tests> Tests = sc.Tests.Where(x => x.Solution == SolId).ToList();
                List<string> ListResult = new List<string>();
                List<bool> ListBoolResult = new List<bool>();
                foreach (Site1.Models.Tests t in Tests)
                {
                    PSRunner runner = new PSRunner();

                    runner.Run(Path.Combine(path, newFileName), t.Input);
                    Thread.Sleep(200);
                    if (runner.IsRunning)
                    {
                        try
                        {
                            runner.p.Kill();
                        }
                        catch
                        {
                            ListResult.Add(t.Input + " : Время вышло");
                            ListBoolResult.Add(false);
                        }
                    }
                    else if (runner.Message == "")
                    {
                        ListResult.Add(t.Input + " : Нет ответа");
                        ListBoolResult.Add(false);
                    }
                    else if (runner.Message != t.Output)
                    {
                        ListResult.Add(t.Input + " : " + runner.Message + " - Неверный ответ");
                        ListBoolResult.Add(false);
                    }
                    else
                    {
                        ListResult.Add(t.Input + " : " + runner.Message + " - Верный ответ");
                        ListBoolResult.Add(true);
                    }
                   // UsersContext uc = new UsersContext();
                   // int UserId = uc.UserProfiles.Where(x => x.UserName == User.Identity.Name).ToList().First().UserId;
                    Site1.Models.Result res = new Models.Result();
                    res.SolutionId = SolId;
                    res.TestId = t.Id;
                    res.UserId = User.Identity.Name;
                    res.Result1 = ListBoolResult.Last() ? "Successfully" : "Fail";
                    res.Date = DateTime.Now;
                    sc.Result.Add(res);              
                }
                sc.SaveChanges();
                ViewBag.Result = ListResult;
                ViewBag.BoolResult = ListBoolResult;
                System.IO.File.Delete(Path.Combine(path, newFileName));

                return View("Result");
            }
            else
            {
                ViewBag.Messange = "Файл не загружен!";
                return View("Student");
            }

        }

    }
}

Site1/Views/Input/Admin.cshtml
@{
    ViewBag.Title = "Вход для администраторов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>
<h2>Пользователи</h2>
<table>
    <thead>
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Admin</td>
            <td>Student</td>
            <td>Teacher</td>
            <td>Функции</td>
        </tr>
    </thead>
    @foreach (Site1.Models.UserProfile U in ViewBag.Users)
    {
        <tr>
            <td>@U.UserId</td>
            <td>@U.UserName</td>
            <td>@Html.CheckBox("Admin",Roles.IsUserInRole(@U.UserName,"Admin"))</td>
            <td>@Html.CheckBox("Student", Roles.IsUserInRole(@U.UserName, "Student"))</td>
            <td>@Html.CheckBox("Teacher", Roles.IsUserInRole(@U.UserName, "Teacher"))</td>
            <td><a href="">Изменить</a> <a href="">Удалить</a></td>
        </tr>
    }
</table>

Site1/Views/Input/EditSolution.cshtml
@model Site1.Models.solutions

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>ViewBag.Title</h1>
<style>
    [name="Description"],[name="Name"] {
        width:100%;
    }
</style>
<form action="/Input/UpdateSolution" method="post">
    @Html.Hidden("Id", (ViewBag.Solution as Site1.Models.solutions).Id)
    @Html.TextBox("Name", (ViewBag.Solution as Site1.Models.solutions).Name)
    <br />
    @Html.TextArea("Description", (ViewBag.Solution as Site1.Models.solutions).Description)
    <input type="submit" value="Сохранить" />
</form>

Site1/Views/Input/Result.cshtml
@{
    ViewBag.Title = "Результаты";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewBag.Title</h1>


<table>
    @{
        int i = 0;
    }
    @foreach (string str in ViewBag.Result)
    {
        string color = ViewBag.BoolResult[i] ? "color:green;" : "color:red;";
        i++;
        <tr style=@color>
            <td>@i</td>
            <td>@str</td>
        </tr>
        
    }
</table>

Site1/Views/Input/Student.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Вход для студентов";
}
<h1>@ViewBag.Title"</h1>
<p style="color:red;">@ViewBag.Messange</p>
<h2>Выберите задание</h2>
<select id="sort_order" onchange="CallActionList($(this).val()); return false;">
    <option disabled selected>
        Выберите задачу
    </option>
    @foreach (var s in (ViewData["ListSolution"] as IEnumerable<Site1.Models.solutions>))
    {
        <option value=@s.Id>@s.Name</option>
    }
</select>
@foreach (var s in (ViewData["ListSolution"] as IEnumerable<Site1.Models.solutions>))
{
    string divId = "desc" + s.Id;
    <div class=desc id=@divId style="display:none;">@s.Description</div>
}
<script>
    function CallActionList(response) {
        $(".desc").each(function ()
        {
            $(this).hide();
        });
        var divId = "#desc" + response;
        $(divId).show();
        $("input[name='solutionId']").val(response);
    };
</script>
<h2>Загрузка файла</h2>

@using (Html.BeginForm("UploadFile", "Input", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="hidden" name="solutionId" value="3" />
    <input type="file" name="fileUpload" /><br />
    <input type="submit" name="Submit" id="SubmitSingle" value="Загрузить" />
}


Site1/Views/Input/Teacher.cshtml
z

Site1/Views/Input/ViewResults.cshtml
@model Site1.Models.Result

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewBag.Title</h1>
<h2>Задание : @ViewBag.Mess</h2>
<table>
    <thead>
        <tr>
            <td>Пользователь</td>
            <td>Тест</td>
            <td>Дата</td>
            <td>Результат</td>
        </tr>
    </thead>
    @foreach (Site1.Models.Result r in ViewBag.Results)
    {
    <tr>
        <td>@r.UserId</td>
        <td>@r.Tests.Input</td>
        <td>@r.Date</td>
        <td>@r.Result1</td>
    </tr>
    }
</table>

Site1/Views/Input/ViewTests.cshtml
@model Site1.Models.Tests

@{
    ViewBag.Title = "ViewTests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ViewBag.Title</h1>
<h2>Задание : @ViewBag.Mess</h2>

<a href="">Добавить тест</a> 
<table>
    <thead>
        <tr>
            <td>Входные данные</td>
            <td>Ответ</td>
            <td>Управление</td>
        </tr>
    </thead>
    @foreach (Site1.Models.Tests t in ViewBag.Tests)
    {
        <tr>
            <td>@t.Input</td>
            <td>@t.Output</td>
            <td><a href="">Редактировать</a> <a>Удалить</a></td>
        </tr>
    }
</table>